# inter_athena.conf (example)
# - 실제 값은 본인 환경에 맞게 수정
# - 민감정보(DB 비번)는 배포/업로드 시 제거 권장

# DB
mysql_host: dpams.ddns.net
mysql_port: 3306
mysql_user: maya
mysql_pass: ##Gmlakd2323
mysql_db  : pokemon_hybrid_web

# (미래) 서버 분리 시 IP/포트
login_ip  : dpams.ddns.net
char_ip   : dpams.ddns.net
map_ip    : dpams.ddns.net
login_port: 6900
char_port : 6121
map_port  : 5121
